"""Audit conformance — runs `scitex-dev ecosystem audit-all`
on this package as a normal pytest test. Generated by
`scitex-dev ecosystem write-audit-test`. Re-run that command
after upgrading scitex-dev to refresh any pin in [dev].
"""

import shutil

import pytest

_SCITEX_DEV_AVAILABLE = shutil.which("scitex-dev") is not None


@pytest.mark.skipif(
    not _SCITEX_DEV_AVAILABLE,
    reason="scitex-dev not installed — add `scitex-dev[cli-audit]` to [dev]",
)
def test_audit_all_returns_without_raising():
    # Arrange
    from scitex_dev.testing import audit_all_for_package

    # Act
    audit_all_for_package("scitex-os")
    # Assert: completing without raising == clean audit.
    assert True
